name: Android CI

on:
  push:
    branches:
      - v1.5_merge_CI_test
  pull_request:
    branches:
      - v1.5_merge_CI_test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: 设置 Gradle 可执行权限
        run: chmod +x gradlew
        
      - name: 设置 Gradle 缓存
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: build

      - name: 运行 Lint & Detekt（代码检查）
        run: ./gradlew lint detekt

      - name: 生成 Detekt Baseline（忽略已知问题）
        run: ./gradlew detektBaseline

      - name: Archive Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: app/build/reports/detekt/

      - name: Archive Detekt Baseline
        uses: actions/upload-artifact@v4
        with:
          name: detekt-baseline
          path: app/baseline.xml

      - name: 运行单元测试
        run: ./gradlew testDebugUnitTest

      - name: 构建 Debug APK
        run: ./gradlew assembleDebug

      - name: 构建 Release APK（未签名）
        run: ./gradlew assembleRelease

      - name: 保存 Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: 保存 Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
